name: PHP Quality and Style

on:
    pull_request:
        branches: [develop]
    push:
        paths:
            - '.github/workflows/phpstan.yml'
            - '**.php'
            - 'phpstan.neon.dist'
            - 'rector.php'

permissions: {}

jobs:
    php-quality-style:
        name: PHP Quality and Style
        runs-on: ubuntu-latest
        timeout-minutes: 5
        permissions:
            contents: write

        steps:
            - name: Harden runner
              uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
              with:
                  egress-policy: audit

            - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
              with:
                  ref: ${{ github.head_ref }}

            - name: Setup PHP
              uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
              with:
                  php-version: '8.2'
                  extensions: json, dom, curl, libxml, mbstring, zip
                  tools: composer:v2
                  coverage: none

            - name: Install dependencies
              run: composer install --no-progress --prefer-dist --optimize-autoloader

            - name: Run Rector
              run: composer refactor

            - name: Commit changes
              uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
              with:
                  commit_message: Refactor code with Rector

            - name: Run Pint
              run: composer format

            - name: Commit changes
              uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
              with:
                  commit_message: Format code with Pint

            - name: Run PHPStan
              run: composer analyse
